### ISSUE TITLE
Quicklook the highlighted entry does not work with Alfred 4

### ISSUE THREAD

**Issue by wenlzhang** [clarencecastillo/alfred-powerthesaurus#11]
I tried to check the output in debug mode, but nothing happened when using SHIFT to preview the highlighted entry.

**Comment by clarencecastillo** [comment]
Seems to be working fine on my side. Does it not just show? Are you using the latest version of Alfred?

![Screenshot 2020-08-06 at 09 42 58](https://user-images.githubusercontent.com/5035728/89481049-789a5500-d7c9-11ea-96dd-13278a2c00e0.gif)

**Comment by wenlzhang** [comment]
When I press SHIFT, I got no response from Alfred and nothing showed. I am using Alfred version 4.1 [1167] on macOS Catalina 10.15.6.

**Comment by clarencecastillo** [comment]
Is this still an issue with you? I was unable to replicate this hence can't help you much. Closing for now. Please re-open if needed.
