### ISSUE TITLE
Add synonyms according to the language used by the user

### ISSUE THREAD

**Issue by rememberYou** [clarencecastillo/alfred-powerthesaurus#3]
First of all, a big thank you for the creation of this package that simplifies the life of many writers.

In order to make this package more accessible to a wider audience, I was wondering if you intended to take into account the language used by the user for the choice of synonyms.

For example, if I am writing a document in French and I cannot find synonyms for my language. I think it would be interesting to add other languages, even if it would require work.

For the detection of the language used in the buffer, maybe you could use [guess-language](https://github.com/tmalsburg/guess-language.el) to avoid recreating the wheel.

**Comment by clarencecastillo** [comment]
Hi @rememberYou, I know this reply is awfully late but thanks for using this workflow!

The content displayed in this workflow is being pulled straight from powerthesaurus.org. Even if there was a way for us to detect the language of the user's query, content-specific features like multi-language support is still ultimately up to the team behind powerthesaurus.org.

I am all in favour of the idea supporting multiple languages. Perhaps we can try suggesting that as [feedback](https://www.powerthesaurus.org/_feedback) to the devs working on Power Thesaurus.

That said, we might still be able to work something out in the near timeline if you could suggest a good French thesaurus website that provides similar features to powerthesaurus.org.
