### ISSUE TITLE
No results returned w/ Alfred 4

### ISSUE THREAD

**Issue by Jdabb** [clarencecastillo/alfred-powerthesaurus#7]
No results returned w/ Alfred 4 I haven't tried with any other version. 
![image](https://user-images.githubusercontent.com/7004123/78593056-0104eb00-7814-11ea-9d2a-0d27fd35d2e4.png)

**Comment by clarencecastillo** [comment]
Did an overhaul to change the way search is being done. New [release](https://github.com/clarencecastillo/alfred-powerthesaurus/releases/tag/v2.1.0) should fix all existing API related errors.
