### ISSUE TITLE
Make compatible with Alfred 3

### ISSUE THREAD

**Issue by bnjmnjns** [clarencecastillo/alfred-powerthesaurus#8]
As discussed in issue #6, the latest version on this plugin no longer works with Alfred 3 though (as has been mentioned) this version doesn't use any alfred 4-specific features so should be easily ported to v3.

Happy to make a PR but will need a little guidance about where to start.
Thanks :)

**Comment by clarencecastillo** [comment]
Hi @bnjmnjns thanks for the interest to port this over to Alfred 3. Now, I'm not very sure if there's a better way to do this, but the following should work:

1. From the root of this project folder, run the `init.sh` script. This should install the Python dependencies. Also, make sure you're using Python 2 (should come default with Mac OS).
2. After that, from Alfred 3, under Workflows, create a new blank workflow.
3. Copy over the details found in the `metadata.json` file when prompted.
4. For the icon, use the `icon.png` file.
5. Create the workflow objects with these configurations:

<img width="827" alt="Screenshot 2020-04-30 at 11 33 32 PM" src="https://user-images.githubusercontent.com/5035728/80729583-06b3cf00-8b3b-11ea-9dbd-4e0f0269b981.png">

Script Filter `pows`:
<img width="787" alt="Screenshot 2020-04-30 at 11 34 50 PM" src="https://user-images.githubusercontent.com/5035728/80729750-48dd1080-8b3b-11ea-8c3e-fd2642a960fd.png">

Script Filter `powa`:
<img width="785" alt="Screenshot 2020-04-30 at 11 35 02 PM" src="https://user-images.githubusercontent.com/5035728/80729756-4a0e3d80-8b3b-11ea-86ab-5db85a2fcf70.png">

Copy to Clipboard:
<img width="566" alt="Screenshot 2020-04-30 at 11 35 11 PM" src="https://user-images.githubusercontent.com/5035728/80729760-4b3f6a80-8b3b-11ea-89ac-5b1a13747ae6.png">

Open URL:
<img width="645" alt="Screenshot 2020-04-30 at 11 35 17 PM" src="https://user-images.githubusercontent.com/5035728/80729762-4c709780-8b3b-11ea-8107-98e6dfbcb9de.png">

When connecting both Script Filters to the Open URL object, enable the Command action modifier.

6. Right click the workflow from the list and select Open in Finder.
7. Copy the contents of the `./src` folder inside the project over to the folder opened in step 6.
8. Test if it works!
9. If all is ok, export the workflow and name it something like `Powerthesaurus-2.1.0-alrfred3.alfredworkflow` or something.

**Comment by clarencecastillo** [comment]
Forgot to mention that in step 7, you should not copy over the `info.plist`. I'm guessing this file is like the manifest version of the workflow objects configuration. Wouldn't have to do step 5 if we can confirm this is actually compatible with Alfred 3.

**Comment by clarencecastillo** [comment]
Closing this for now. Please let me know if anyone else wants to pick this up and I'll re-open this issue.
